<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Artist;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;

/**
 * ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends \Doctrine\ORM\EntityRepository
{


    public function find($id, $lockMode = null, $lockVersion = null)
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->where('a.id=:id')
            ->setParameter('id', $id);

        $artist = $queryBuilder->getQuery()->getOneOrNullResult();

        return $artist;

    }

    public function findAll()
    {

        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->orderBy('a.name','ASC');
        $artists = $queryBuilder->getQuery()->execute();

        return $artists;
    }



}
