<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Playlist;
use AppBundle\Entity\Track;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->orderBy('p.name','ASC');
        $playlists = $queryBuilder->getQuery()->execute();

        return $playlists;

    }

    public function find($id, $lockMode = null, $lockVersion = null)
    {
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->where('p.id =  :id')
            ->setParameter('id',$id);

        $playlist = $queryBuilder->getQuery()->getOneOrNullResult();

        return $playlist;
    }

    public function calculateDuration(Playlist $playlist){
        $queryBuilder = $this->createQueryBuilder('p');
        $queryBuilder->select('DISTINCT SUM(t.duration)')
            ->innerJoin('p.tracks','t')
            ->where("p = :playlist")
            ->setParameter('playlist',$playlist);

        $duration = $queryBuilder->getQuery()->getOneOrNullResult()[1];



        return $duration;

    }

}
