<?php

namespace AppBundle\Repository;

/**
 * TrackBisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackBisRepository extends \Doctrine\ORM\EntityRepository
{
}
