security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    user: { password: userpass, roles: 'ROLE_USER' }
                    admin: { password: adminpass, roles: 'ROLE_ADMIN' }

    firewalls:
        main:
            pattern: /
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: 'ROLE_ADMIN' }